version: '3'

networks:
  strategio-network:

services:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    #container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/elastic/es1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - strategio-network

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    #container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/elastic/es2:/usr/share/elasticsearch/data
    networks:
      - strategio-network

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    #container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/elastic/es3:/usr/share/elasticsearch/data
    networks:
      - strategio-network